package com.safekeep.backend.enums;

public enum AuditEventType {
    CHECKIN,
    STATUS_TRANSITION,
    VAULT_ITEM_CREATED,
    VAULT_ITEM_UPDATED,
    VAULT_ITEM_DELETED,
    RECIPIENT_ADDED,
    RECIPIENT_UPDATED,
    RECIPIENT_DELETED,
    CONTENT_RELEASED,
    LOGIN,
    LOGOUT,
    REGISTER,
    REMINDER_SENT,
    FINAL_WARNING_SENT,
    SETTINGS_UPDATED,
    RELEASE_TOKEN_ACCESSED
}
